aadibd/aadibd/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('interview/', include('test_aadi.urls')),
    path('', include('test_aadi.urls')),
]

aadibd/test_aadi/urls.py
from django.urls import path

from . import views

app_name='test_aadi'
urlpatterns = [    
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.SessionDetailView.as_view(),name='sessiondetail'),
    path('add/',views.InterviewCreate.as_view(),name='interview-add'),
 
]

aadibd/test_aadi/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Interview(models.Model):
    Title=models.CharField(max_length=200)
    Date=models.DateField()
class Session(models.Model):
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE)
    Title=models.CharField(max_length=200)
    Date=models.DateField()
    Applicants=models.CharField(max_length=250)
class Applicants(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    Name=models.CharField(max_length=200)

aadibd/test_aadi/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Interview,Session,Applicants
# Create your views here.
class IndexView(generic.ListView):
    template_name='index.html'
    context_object_name='interviews'
    def get_queryset(self):
        return Interview.objects.all()
class SessionDetailView(generic.DetailView):
    model=Interview
    context_object_name='sessions'
    template_name='session_detail.html'
class InterviewCreate(CreateView):
    model=Interview
    fields=['Title','Date']
    template_name='interviewform.html'

aadibd/test_aadi/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interview Details</title>
</head>
<body>
    <h1 style="text-align: center;">Welcome to the Interview Application</h1>
    {% if interviews %}
        <ol>
            {% for interview in interviews %}
            
            <li><a href="{% url 'test_aadi:sessiondetail' interview.pk %}">
                <ul style="list-style: none;">
                    <li>{{ interview.Title }}</li>
                    <li>{{ interview.Date }}</li>
                </ul>
            </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <h3>Nothing Added Yet</h3>
    {% endif %}
    <a href="{% url 'test_aadi:interview-add' %}"> <button>Add Interview</button> </a>
</body>
</html>

aadibd/test_aadi/templates/interviewform.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interview Add</title>
</head>

<body>
    <form action="" method=POST>
        {% csrf_token %}
        {% for field in form %}
        <label>{{ field.label }}</label>
        <div>{{ field }}</div><br>
        {% endfor %}
        <a href="#"> <button type='submit'>Submit</button> </a>
    </form>
</body>

</html>

aadibd/test_aadi/templates/session_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Session Detail</title>
</head>
<body>
    <h2>Welcome to Session Detail</h2>
    <ol>
        {% for choice in sessions.session_set.all %}
        <li>{{choice.Title}}</li>
        {% endfor %}
    </ol>
</body>
</html>